title: SleeepinX
subtitle: SleeepinX
description: SleeepinX
author: SleeepinX
language: zh-CN
timezone: Asia/Hong_Kong
url: https://sleeepyin.github.io
root: /sleeepinx/
permalink: :year/:month/:day/:title/
pretty_urls:
  trailing_index: false
  trailing_html: false

source_dir: source
public_dir: docs
theme: landscape
archive_dir: archives
category_dir: categories
tag_dir: tags
post_asset_folder: false

highlight:
  enable: true
  line_number: true

feed:
  type: atom
  path: atom.xml
  limit: 20

theme_config:
  menu:
    首页: /
    归档: /archives/
  subtitle: SleeepinX
  rss: /atom.xml
